version: 0.0
os: linux
files:
  - source: target/devops-practice-0.0.1-SNAPSHOT.jar
    destination: /home/cloud_user
hooks:
  BeforeInstall:
    - location: scripts/run.sh
  AfterInstall:
    - location: scripts/run.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 3600
  ValidateService:
    - location: scripts/run.sh
