version: 0.0
os: linux
files:
  - source: target/devops-practice-0.0.1-SNAPSHOT.jar
    destination: /home/cloud_user
hooks:
  BeforeInstall:
    - location: scripts/run.sh
      runas: cloud_user
  AfterInstall:
    - location: scripts/run.sh
      timeout: 180
      runas: cloud_user
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 3600
      runas: cloud_user
  ValidateService:
    - location: scripts/run.sh
      runas: cloud_user
