version: 0.2
         
phases:
  install:
    commands:
      - echo 'hello'
  pre_build:
    commands:
      - echo 'hello'
    
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo 'hello'
artifacts:
  files:
    - target/devops-practice-0.0.1-SNAPSHOT.jar
