version: 0.2
         
phases:
  install:
    commands:
      - echo 'hello'
  pre_build:
    commands:
      - echo 'hello'
    
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo 'hello'
